version: "3.8"

services:
  coordinator:
    build: ./coordinator
    volumes:
      - ./output:/multi3_coord_ws/src/multi3_tests/multi3_tests/results
    container_name: coordinator
    ports:
      - "5000:5000"

  executor1:
    build: ./executor
    container_name: executor1
    environment:
      - DISPLAY=${DISPLAY}
      - REAL_ROBOT=0
      - EXECUTOR_ID=executor1
      - ROBOT_NAME=robot_1
      - TB_ID=Turtlebot_02489
      - ROS_ENV=ros_humble
      - ROS_DOMAIN=0
      - COORDINATOR_URL=http://coordinator:5000
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - coordinator
    network_mode: host  # optional: required for some ROS GUI tools like RViz to find ROS master
    privileged: true

  executor2:
    build: ./executor
    container_name: executor2
    environment:
      - DISPLAY=${DISPLAY}
      - REAL_ROBOT=0
      - EXECUTOR_ID=executor2
      - ROBOT_NAME=robot_2
      - TB_ID=Turtlebot_02490
      - ROS_ENV=ros_humble
      - ROS_DOMAIN=1
      - COORDINATOR_URL=http://coordinator:5000
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - coordinator
    network_mode: host  # optional: required for some ROS GUI tools like RViz to find ROS master


